grpc:
  port: ":9092"
  host: "localhost"

grpcgateway:
  port: ":8082"
  host: "localhost"

database:
  port: 5432
  host: "localhost"
  name: "hospital_service"
  user: "postgres"
  password: 5822

migrationspath: "test" 