version: '3'

vars:
  LOCAL_BIN: '{{.ROOT_DIR}}/bin'

tasks:
  install-deps:
    desc: Install dependencies.
    cmds:
      - GOBIN={{.LOCAL_BIN}} go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
      - GOBIN={{.LOCAL_BIN}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
      - GOBIN={{.LOCAL_BIN}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.22.0

  get-deps:
    desc: Get dependencies.
    cmds:
      - go get -u github.com/ilyakaznacheev/cleanenv
      - go get -u github.com/jackc/pgx/v5
      - go get -u github.com/jackc/pgx/v5/pgxpool
      - go get -u google.golang.org/protobuf/cmd/protoc-gen-go
      - go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
      - go get -u github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
      - go get -u github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway

  generate:
    desc: Generate Golang code for all services. 
    cmds:
      - task: generate-account-service
      - task: generate-document-service
      - task: generate-hospital-service
      - task: generate-timetable-service

  generate-account-service:
    desc: Generate Golang code for account service from .proto file.
    cmds:
      - protoc -I $GOPATH/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.16.0/third_party/googleapis -I proto proto/account-service/account.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative

  generate-document-service:
    desc: Generate Golang code for document service from .proto file.
    cmds:
      - protoc -I $GOPATH/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.16.0/third_party/googleapis -I proto proto/document-service/document.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative

  generate-hospital-service:
    desc: Generate Golang code for hospital service from .proto file.
    cmds:
      - protoc -I $GOPATH/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.22.0 -I $GOPATH/pkg/mod/github.com/googleapis/googleapis@v0.0.0-20241001214639-16a1580c06b3 -I proto proto/hospital-service/hospital.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative --grpc-gateway_out=./gen/go --grpc-gateway_opt=paths=source_relative --openapiv2_out=./swagger --openapiv2_opt=logtostderr=true

  generate-timetable-service:
    desc: Generate Golang code for timetable service from .proto file.
    cmds:
      - protoc -I $GOPATH/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.16.0/third_party/googleapis -I proto proto/timetable-service/timetable.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative   